import { Injectable } from '@angular/core';
import { Store } from '../interfaces/store';

@Injectable({
  providedIn: 'root',
})
export class StoreService {
  store: Store[] = [
    // コンビニ
    { id: 'seicomart', name: 'セイコーマート', type: 'real' },
    { id: 'seven-eleven', name: 'セブン‐イレブン', type: 'real' },
    { id: 'dailyyamazaki', name: 'デイリーヤマザキ', type: 'real' },
    { id: 'familymart', name: 'ファミリーマート', type: 'real' },
    { id: 'popla', name: 'ポプラ', type: 'real' },
    { id: 'ministop', name: 'ミニストップ', type: 'real' },
    { id: 'lawson', name: 'ローソン', type: 'real' },
    { id: 'naturallawson', name: 'ナチュラルローソン', type: 'real' },
    { id: 'lawson100', name: 'ローソンストア100', type: 'real' },
    // 総合スーパー
    { id: 'akafudado', name: '赤札堂', type: 'real' },
    { id: 'abab', name: 'ABAB', type: 'real' },
    { id: 'ok', name: 'OK', type: 'real' },
    { id: 'otani', name: 'スーパーオータニ', type: 'real' },
    { id: 'superalps', name: 'スーパーアルプス', type: 'real' },
    { id: 'okkasan', name: 'スーパーおっ母さん', type: 'real' },
    { id: 'seiyu', name: '西友', type: 'real' },
    { id: 'sekichu', name: 'セキチュー', type: 'real' },
    { id: 'itoyokado', name: 'イトーヨーカドー', type: 'real' },
    { id: 'yorkmart', name: 'ヨークマート', type: 'real' },
    { id: 'sotetsurosen', name: 'そうてつローゼン', type: 'real' },
    { id: 'takeya', name: '多慶屋', type: 'real' },
    { id: 'daikokuya', name: '大黒屋', type: 'real' },
    { id: 'es-tajima', name: 'エネルギースーパーたじま', type: 'real' },
    { id: 'giga-pearl', name: 'ギガパール', type: 'real' },
    { id: 'giga-mart', name: 'ギガマート', type: 'real' },
    { id: 'nakamuraya', name: 'ナカムラヤ', type: 'real' },
    { id: 'hallo-mart', name: 'ハローマート', type: 'real' },
    { id: 'bonvisage', name: 'ボンヴィサージュ', type: 'real' },
    { id: 'yaoyoshi', name: 'ヤオヨシ', type: 'real' },
    { id: 'daiyu', name: 'ダイユー', type: 'real' },
    { id: 'tokyustore', name: '東急ストア', type: 'real' },
    { id: 'tobustore', name: '東武ストア', type: 'real' },
    { id: 'torisen_02', name: 'とりせん', type: 'real' },
    { id: 'biga', name: 'ビッグ・エー', type: 'real' },
    { id: 'bigyosan', name: 'ビッグヨーサン', type: 'real' },
    { id: 'mom', name: 'フードマーケットマム', type: 'real' },
    { id: 'beisia', name: 'ベイシア', type: 'real' },
    { id: 'belc', name: 'ベルク', type: 'real' },
    { id: 'maruya', name: 'マルヤ', type: 'real' },
    { id: 'joyfoods', name: 'ジョイフーズ', type: 'real' },
    { id: 'yamaguchi', name: 'ヤマグチ', type: 'real' },
    { id: 'mrmax_1', name: 'MrMax', type: 'real' },
    { id: 'yamaichi', name: 'ヤマイチ', type: 'real' },
    { id: 'yamaya', name: 'やまや', type: 'real' },
    { id: 'yucoop', name: 'ユーコープ', type: 'real' },
    { id: 'life', name: 'ライフ', type: 'real' },
    { id: 'likaman', name: 'リカーマウンテン', type: 'real' },
    { id: 'ysmart', name: 'ワイズマート', type: 'real' },
    { id: 'watahan', name: '綿半', type: 'real' },
    // ドラッグストア
    { id: 'ainztulpe', name: 'アインズ&トルペ', type: 'real' },
    { id: 'ains', name: 'アインズ', type: 'real' },
    { id: 'lipsandhips', name: 'LIPS', type: 'real' },
    { id: 'welcia', name: 'ウエルシア', type: 'real' },
    { id: 'hacdrug', name: 'ハックドラッグ', type: 'real' },
    { id: 'bbon', name: 'B', type: 'real' },
    { id: 'maruedrug', name: 'マルエドラッグ', type: 'real' },
    { id: 'kawachi', name: 'カワチ薬品', type: 'real' },
    { id: 'kimuraya', name: 'キムラヤ', type: 'real' },
    { id: 'kirindo', name: 'キリン堂', type: 'real' },
    { id: 'aoki', name: 'クスリのアオキ', type: 'real' },
    { id: 'create', name: 'クリエイトエス・ディー', type: 'real' },
    { id: 'kokumin', name: 'コクミンドラッグ', type: 'real' },
    { id: 'cocokarafine', name: 'ココカラファイン', type: 'real' },
    { id: 'yamadadrug', name: 'コスメティクスアンドメディカル', type: 'real' },
    { id: 'satsudora', name: 'サツドラ', type: 'real' },
    { id: 'sundrug', name: 'サンドラッグ', type: 'real' },
    { id: 'sanyoyakuhin', name: '三洋薬品HBC株式会社', type: 'real' },
    { id: 'sugiyakkyoku', name: 'スギ薬局', type: 'real' },
    { id: 'japan', name: 'ジャパン', type: 'real' },
    { id: 'sekiyakuhin', name: 'セキ薬局', type: 'real' },
    { id: 'daikokudrug', name: 'ダイコクドラッグ', type: 'real' },
    { id: 'tsuruhadrug', name: 'ツルハドラッグ', type: 'real' },
    { id: 'fukutaro', name: 'くすりの福太郎', type: 'real' },
    { id: 'tomods', name: 'トモズ', type: 'real' },
    { id: 'drag11', name: 'ドラッグイレブン', type: 'real' },
    { id: 'bigdrug', name: 'ビックドラッグ', type: 'real' },
    { id: 'kozimadrug', name: 'コジマドラッグ', type: 'real' },
    { id: 'seims', name: 'セイムス', type: 'real' },
    { id: 'matsumoto_kiyosi', name: 'マツモトキヨシ', type: 'real' },
    // 飲食
    { id: 'ueshima', name: '上島珈琲店', type: 'real' },
    { id: 'ebisufoodhall', name: 'EBISU FOOD HALL', type: 'real' },
    { id: 'origin', name: 'キッチンオリジン', type: 'real' },
    { id: 'renge', name: 'れんげ食堂 Toshu', type: 'real' },
    { id: 'keyscafe', name: 'KeysCafe', type: 'real' },
    { id: 'kyotokatsugyu', name: '京都勝牛', type: 'real' },
    { id: 'kurazushi', name: 'くら寿司', type: 'real' },
    { id: 'kfc', name: 'ケンタッキーフライドチキン', type: 'real' },
    { id: 'gyushige', name: '元氣七輪焼肉 牛繁', type: 'real' },
    { id: 'gyukaku', name: '牛角', type: 'real' },
    { id: 'freshness', name: 'フレッシュネスバーガー', type: 'real' },
    { id: 'kappa', name: 'かっぱ寿司', type: 'real' },
    { id: 'suteki', name: 'ステーキ宮', type: 'real' },
    { id: 'onyasai', name: '温野菜', type: 'real' },
    { id: '31ice_cream', name: 'サーティワンアイスクリーム', type: 'real' },
    { id: 'yakinikubanri', name: '焼肉万里', type: 'real' },
    { id: 'saintmarccafe', name: 'サンマルクカフェ', type: 'real' },
    { id: 'anan', name: '七輪焼肉 安安', type: 'real' },
    { id: 'gusto', name: 'ガスト', type: 'real' },
    { id: 'grazie', name: 'グラッチェガーデンズ', type: 'real' },
    { id: 'syabuyo2', name: 'しゃぶ葉', type: 'real' },
    { id: 'jonathan', name: 'ジョナサン', type: 'real' },
    { id: 'bamiyan', name: 'バーミヤン', type: 'real' },
    { id: 'dennys', name: 'デニーズ', type: 'real' },
    { id: 'dennysdiner', name: 'DennysDiner', type: 'real' },
    { id: 'grandiner', name: 'GranDiner', type: 'real' },
    { id: 'kojimachi', name: '麹町珈琲（麹は旧字体）', type: 'real' },
    { id: 'shiroyagi', name: '白ヤギ珈琲店', type: 'real' },
    { id: 'taiyounogrill', name: '太陽のグリル', type: 'real' },
    { id: 'alohatable', name: 'アロハテーブル', type: 'real' },
    { id: 'ichikokudou', name: '壱鵠堂', type: 'real' },
    { id: 'katsuan', name: 'かつ庵', type: 'real' },
    { id: 'sukiya', name: 'すき家', type: 'real' },
    { id: 'setoudon', name: '瀬戸うどん', type: 'real' },
    { id: 'tamonan', name: 'たもん庵', type: 'real' },
    { id: 'tenkaichi', name: '天下一', type: 'real' },
    { id: 'denmaru', name: '伝丸', type: 'real' },
    { id: 'nakau', name: 'なか卯', type: 'real' },
    { id: 'nabekura', name: '菜べくら', type: 'real' },
    { id: 'hanayayohei', name: '華屋与兵衛', type: 'real' },
    { id: 'hamazushi', name: 'はま寿司', type: 'real' },
    { id: 'bigboy', name: 'BigBoy', type: 'real' },
    { id: 'morivacoffee', name: 'モリバコーヒー', type: 'real' },
    { id: 'wasyokuyohei', name: '和食よへい', type: 'real' },
    { id: 'gindako', name: '築地銀だこ', type: 'real' },
    { id: 'hanbey', name: '薄利多賣半兵ヱ', type: 'real' },
    { id: 'hanamaruudon', name: 'はなまるうどん', type: 'real' },
    { id: '669', name: 'bb.q OLIVE CHICKEN cafe', type: 'real' },
    { id: 'hidakaya_hiday', name: '日高屋', type: 'real' },
    { id: 'firstkitchen_01', name: 'ファーストキッチン', type: 'real' },
    {
      id: 'firstkitchen',
      name: 'ウェンディーズ・ファーストキッチン',
      type: 'real',
    },
    { id: 'hondanacoffer', name: '本棚珈琲', type: 'real' },
    { id: 'matsuya', name: '松屋', type: 'real' },
    { id: 'tonkatsumatsunoya', name: '松のや', type: 'real' },
    { id: 'yoshinoya', name: '吉野家', type: 'real' },
    { id: 'texmix', name: 'TEXMEX FACTORY', type: 'real' },
    { id: 'fridays', name: 'TGI フライデーズ', type: 'real' },
    { id: 'nikusuta', name: 'にくスタ', type: 'real' },
    { id: 'ws', name: 'WANGS GARDEN', type: 'real' },
    // 宅配
    { id: 'deliveryskylark', name: 'すかいらーくグループの宅配', type: 'real' },
    { id: 'strawberrycones', name: 'ストロベリーコーンズ', type: 'real' },
    { id: 'napolinokama', name: 'ナポリの窯', type: 'real' },
    { id: 'delis', name: 'デリズ', type: 'real' },
    { id: 'pizza_pockets', name: 'ピザポケット', type: 'real' },
    { id: 'pizzala', name: 'ピザーラ', type: 'real' },
    { id: 'kakiyazushi', name: '柿家鮨', type: 'real' },
    // 居酒屋
    { id: 'kanteki', name: 'かんてきや', type: 'real' },
    { id: 'fuziyamasakaya', name: 'フジヤマ桜', type: 'real' },
    { id: 'isomaru', name: '磯丸水産', type: 'real' },
    { id: 'ichigorou', name: '餃子製造販売店 いち五郎', type: 'real' },
    { id: 'toriyoshi', name: '手羽先唐揚専門店 鳥良', type: 'real' },
    { id: 'toriyoshisyoten', name: '鳥良商店', type: 'real' },
    { id: 'kinnokura', name: '金の蔵', type: 'real' },
    { id: 'akamaruya', name: 'アカマル屋', type: 'real' },
    { id: 'tohokenbunroku', name: '東方見聞録', type: 'real' },
    { id: 'baribaridori', name: 'バリバリ鶏', type: 'real' },
    { id: 'sumibiizaykayaen', name: '炭火居酒屋 炎', type: 'real' },
    { id: 'hananomai_01', name: 'はなの舞', type: 'real' },
    { id: 'tometeba', name: 'とめ手羽', type: 'real' },
    { id: 'dartsshoptito', name: 'Darts Shop TiTO', type: 'real' },
    { id: 'sushiuogin', name: '魚銀', type: 'real' },
    { id: 'uotami', name: '魚民', type: 'real' },
    { id: 'uoman', name: '北海道 魚萬', type: 'real' },
    { id: 'uoman01', name: '濱焼北海道魚萬', type: 'real' },
    { id: 'uoman02', name: '横濱 魚萬', type: 'real' },
    { id: 'utanosuke', name: '歌之助', type: 'real' },
    { id: 'uchikuru', name: 'うちくる', type: 'real' },
    { id: 'oideyo', name: 'おいで屋', type: 'real' },
    { id: 'kuroda', name: '串かつ黒田めでた家', type: 'real' },
    { id: 'kuromaru', name: 'くろ○', type: 'real' },
    { id: 'shitokuya', name: '白木屋', type: 'real' },
    { id: 'sennen', name: '千年の宴', type: 'real' },
    { id: 'tsukinoutage', name: '月の宴', type: 'real' },
    { id: 'niatori', name: '鶏のGeorge', type: 'real' },
    { id: 'fukufukuya', name: '福福屋', type: 'real' },
    { id: 'takadatori', name: '豊後高田どり酒場', type: 'real' },
    { id: 'mitsuecyan', name: 'みつえちゃん', type: 'real' },
    { id: 'mekiki', name: '目利きの銀次', type: 'real' },
    { id: 'medetaya', name: 'めでた家', type: 'real' },
    { id: 'yamauchi', name: '山内農場', type: 'real' },
    { id: 'warawara', name: '笑笑', type: 'real' },
    { id: 'wai', name: 'バラエティ厨房 輪囲', type: 'real' },
    { id: 'robokichi', name: 'ROBOT KICHI', type: 'real' },
    { id: 'watami02', name: '和民', type: 'real' },
    { id: 'watami01', name: '坐・和民', type: 'real' },
    { id: 'gohan', name: 'GOHAN', type: 'real' },
    { id: 'torimero', name: '三代目鳥メロ', type: 'real' },
    { id: 'maguro', name: 'まぐろ漁業団', type: 'real' },
    { id: 'miraizaka', name: 'ミライザカ', type: 'real' },
    // 家電量販
    { id: 'edon', name: 'エディオン', type: 'real' },
    { id: 'ksdenki', name: 'ケーズデンキ', type: 'real' },
    { id: 'denkichi', name: 'デンキチ', type: 'real' },
    { id: 'nojima', name: 'ノジマ', type: 'real' },
    { id: 'biccamera', name: 'ビックカメラ', type: 'real' },
    { id: 'kozima', name: 'コジマ', type: 'real' },
    { id: 'sofmap', name: 'ソフマップ', type: 'real' },
    { id: 'pcdepo', name: 'PC DEPOT', type: 'real' },
    { id: 'beishia', name: 'ベイシア電器', type: 'real' },
    { id: 'yamada', name: 'ヤマダ電機', type: 'real' },
    { id: 'tsukumo', name: 'TSUKUMO', type: 'real' },
    { id: 'best', name: 'ベスト電器', type: 'real' },
    { id: 'matsuyadenki', name: 'マツヤデンキ', type: 'real' },
    { id: 'pasocon', name: 'パソコン工房', type: 'real' },
    // 書籍
    { id: 'tsutaya', name: 'TSUTAYA', type: 'real' },
    { id: 'furuhonichiba', name: '古本市場', type: 'real' },
    { id: 'tranoana', name: 'とらのあな', type: 'real' },
    { id: 'haruya', name: '明屋書店', type: 'real' },
    { id: 'book1st', name: 'ブックファースト', type: 'real' },
    { id: 'maruzen', name: 'MARUZEN', type: 'real' },
    { id: 'junkudo', name: 'ジュンク堂', type: 'real' },
    { id: 'rashinban', name: 'らしんばん', type: 'real' },
    { id: 'libro', name: 'LIBRO', type: 'real' },
    { id: 'ayumibooks', name: 'あゆみBOOKS', type: 'real' },
    { id: 'orion', name: 'オリオン書房', type: 'real' },
    { id: 'parcobook', name: 'パルコブックセンター', type: 'real' },
    { id: 'bunkitsu', name: '文喫', type: 'real' },
    { id: 'bunrokudou', name: '文禄堂', type: 'real' },
    { id: 'miomio', name: 'miomio', type: 'real' },
    { id: 'yomuyomu', name: 'よむよむ', type: 'real' },
    { id: 'wandergoo', name: 'ワンダーGOO', type: 'real' },
    // ファッション
    { id: 'babydoll', name: 'ベビードール', type: 'real' },
    { id: 'jeans', name: 'ジーンズメイト', type: 'real' },
    { id: 'outdoor', name: 'Outdoor', type: 'real' },
    { id: 'takaq', name: 'TAKA-Q', type: 'real' },
    { id: 'grandback', name: 'GRAND BACK', type: 'real' },
    { id: 'diesel', name: 'DIESEL', type: 'real' },
    { id: 'haruyama', name: 'はるやま', type: 'real' },
    { id: 'perfectsuitfactory', name: 'Perfect Suit FActory', type: 'real' },
    { id: 'fithouse', name: 'FIT HOUSE', type: 'real' },
    { id: 'machouse', name: 'マックハウス', type: 'real' },
    { id: 'righton', name: 'ライトオン', type: 'real' },
    // 百貨店
    { id: 'odakyu', name: '小田急百貨店', type: 'real' },
    { id: 'grandberrypark', name: 'グランベリーパーク', type: 'real' },
    { id: 'takashimaya', name: '高島屋', type: 'real' },
    { id: 'dutyfree', name: '髙島屋免税店SHILLA&amp;ANA', type: 'real' },
    { id: 'lacittadella', name: 'LA CITTADELLA', type: 'real' },
    { id: 'nihonkukobuilding', name: '日本空港ビルディング', type: 'real' },
    { id: 'iiyo', name: 'イーヨ!!', type: 'real' },
    { id: 'oazo', name: 'oazo', type: 'real' },
    { id: 'shinmarubiru', name: '新丸ビル', type: 'real' },
    { id: 'tokia', name: 'TOKIA', type: 'real' },
    { id: 'nijubashisquare', name: '二重橋スクエア', type: 'real' },
    { id: 'bricksquare', name: 'ブリックスクエア', type: 'real' },
    { id: 'marubiru', name: '丸ビル', type: 'real' },
    { id: 'randmarkplaza', name: 'ランドマークプラザ', type: 'real' },
    // メガネ•コンタクト
    { id: 'aimegane', name: 'アイメガネ', type: 'real' },
    { id: 'owndays', name: 'OWNDAYS', type: 'real' },
    { id: 'jins', name: 'JINS', type: 'real' },
    { id: 'zoff', name: 'Zoff', type: 'real' },
    {
      id: 'cyuoucontact',
      name: '中央コンタクト・フラワーコンタクト',
      type: 'real',
    },
    { id: 'heartup', name: 'ハートアップ', type: 'real' },
    { id: 'parimiki', name: 'パリミキ', type: 'real' },
    { id: 'meganesuper', name: 'メガネスーパー', type: 'real' },
    { id: 'fujicontact', name: '富士コンタクト', type: 'real' },
    { id: 'meganeichiba', name: '眼鏡市場', type: 'real' },
    { id: 'alook', name: 'ALOOK', type: 'real' },
    { id: 'meganedrug', name: 'メガネドラッグ', type: 'real' },
    { id: 'itagakiglasses', name: 'メガネのイタガキ', type: 'real' },
    // ショッピング
    { id: 'akachan', name: 'アカチャンホンポ', type: 'real' },
    { id: 'animate', name: 'アニメイト', type: 'real' },
    { id: 'gamers', name: 'ゲーマーズ', type: 'real' },
    { id: 'ikea', name: 'イケア', type: 'real' },
    { id: 'ichibashi', name: 'イシバシ楽器', type: 'real' },
    { id: 'windsor', name: 'ウインザーラケットショップ', type: 'real' },
    { id: 'kameyatsurigu', name: 'かめや釣具', type: 'real' },
    { id: 'kitamura', name: 'カメラのキタムラ', type: 'real' },
    { id: 'casting', name: 'キャスティング', type: 'real' },
    { id: 'geo', name: 'GEO', type: 'real' },
    { id: 'geomobile', name: 'GEOmobile', type: 'real' },
    { id: '2ndstreet', name: '2ndSTREET', type: 'real' },
    { id: 'cyclespot', name: 'サイクルスポット', type: 'real' },
    {
      id: 'cycle-spot-le',
      name: 'サイクルスポット&amp;ル・サイク',
      type: 'real',
    },
    { id: 'cb-asahi', name: 'サイクルベースあさひ', type: 'real' },
    { id: 'shimamura', name: '島村楽器', type: 'real' },
    { id: 'dream', name: '手芸センター ドリーム', type: 'real' },
    { id: 'stepsports', name: 'SteP SPORTS', type: 'real' },
    { id: 'surugaya', name: '駿河屋', type: 'real' },
    { id: 'sonystore', name: 'ソニーストア', type: 'real' },
    { id: 'daiso', name: 'DAISO', type: 'real' },
    { id: 'dulton', name: 'DULTON', type: 'real' },
    { id: 'chiyoda', name: 'チヨダ', type: 'real' },
    { id: 'shoeplaza', name: 'シュープラザ', type: 'real' },
    {
      id: 'tokyoshoesretailingcenter',
      name: '東京靴流通センター',
      type: 'real',
    },
    { id: 'point', name: '釣具のポイント', type: 'real' },
    { id: 'golftsuruya', name: 'つるやゴルフ', type: 'real' },
    { id: 'toysrus', name: 'トイザらス', type: 'real' },
    { id: 'tokyuhands', name: '東急ハンズ', type: 'real' },
    { id: 'hobbyzone', name: 'ホビーゾーン', type: 'real' },
    // レジャー•娯楽
    { id: 'kaikatsuclub', name: '快活CLUB', type: 'real' },
    { id: 'karaokekan', name: 'カラオケ館', type: 'real' },
    { id: 'usland', name: 'Kids US.LAND', type: 'real' },
    { id: 'cotedazur', name: 'コート・ダ・ジュール', type: 'real' },
    { id: 'crokkeclub', name: 'コロッケ倶楽部', type: 'real' },
    { id: 'joysound', name: 'JOYSOUND', type: 'real' },
    { id: 'tackleberry', name: 'タックルベリー', type: 'real' },
    { id: 'cinecitta', name: 'CINECITTA', type: 'real' },
    { id: 'bigecho', name: 'BIGECHO', type: 'real' },
    { id: 'yomiuri', name: 'よみうりランド', type: 'real' },
    { id: 'round1', name: 'ラウンドワン', type: 'real' },
    // 交通
    { id: 'enoshima', name: '江ノ島タクシー', type: 'real' },
    { id: 'shonanmonorail', name: '湘南モノレール', type: 'real' },
    { id: 'nihonchuou', name: '日本中央交通', type: 'real' },
    { id: 'royallimousine', name: 'ロイヤルリムジン', type: 'real' },
    { id: 'orientaltaxi', name: 'オリエンタルタクシー', type: 'real' },
    {
      id: 'japanpremiumtokyo',
      name: 'ジャパンプレミアム 東京シティエスコート',
      type: 'real',
    },
    { id: 'ichinisan', name: '一二三交通自動車', type: 'real' },
    // 宿泊•旅
    { id: 'his', name: 'H.I.S.', type: 'real' },
    { id: 'juraku', name: '聚楽', type: 'real' },
    { id: 'tabix', name: 'タビックスジャパン', type: 'real' },
    { id: 'toyoko-inn', name: '東横イン', type: 'real' },
    { id: 'nikkoniigata', name: 'ホテル日航新潟', type: 'real' },
    { id: 'monterey-akasaka', name: 'ホテルモントレ赤坂', type: 'real' },
    { id: 'monterey-ginza', name: 'ホテルモントレ銀座', type: 'real' },
    { id: 'monterey-hanzomon', name: 'ホテルモントレ半蔵門', type: 'real' },
    { id: 'monterey-yokohama', name: 'ホテルモントレ横浜', type: 'real' },
    {
      id: 'monterey-lasoeurginza',
      name: 'ホテルモントレ ラ・スールギンザ',
      type: 'real',
    },
    { id: 'hotelmystays', name: 'ホテルマイステイズ', type: 'real' },
    {
      id: 'hotelmystayspremiem',
      name: 'ホテルマイステイズプレミア',
      type: 'real',
    },
    { id: 'elexstay', name: 'フレックスステイイン', type: 'real' },
    { id: 'monthlyresistays', name: 'マンスリーレジステイズ', type: 'real' },
    {
      id: 'washington-hotel-plaza',
      name: 'ワシントンホテルプラザ',
      type: 'real',
    },
    { id: 'randbhotel', name: 'R&amp;Bホテル', type: 'real' },
    // その他
    { id: 'arthikkoshi', name: 'アート引越センター', type: 'real' },
    { id: 'aichintai', name: 'ai賃貸', type: 'real' },
    { id: 'arisan', name: 'アリさんマークの引越社', type: 'real' },
    { id: 'ash', name: 'アッシュ', type: 'real' },
    { id: 'diamondeyes', name: 'ダイヤモンドアイズ', type: 'real' },
    { id: 'yellowhat', name: 'イエローハット', type: 'real' },
    { id: 'usachan2', name: 'うさちゃんクリーニング', type: 'real' },
    { id: 'empire', name: 'エンパイアー', type: 'real' },
    { id: 'autobacs', name: 'オートバックス', type: 'real' },
    { id: 'nihoncyusyajokaihatsu', name: '日本駐車場開発', type: 'real' },
    { id: 'bikeou', name: 'バイク王', type: 'real' },
    { id: 'fuji', name: 'Fuji', type: 'real' },
    { id: 'headlight', name: 'HEADLIGHT', type: 'real' },
    { id: 'ricoland', name: 'RICOLAND', type: 'real' },
    { id: 'relxle', name: 'りらくる', type: 'real' },
  ];

  constructor() {}
}
